# -*- coding: utf-8 -*-
"""cosine_similarity_solar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgqEXEmCmbB1T71-2HsgO1-2jdTUyS8B
"""

from google.colab import files

uploaded=files.upload()

import pandas as pd

similarSolar = pd.read_csv('cssolar.csv')

similarSolar.head(2)

similarSolar.columns

cleanSolar = similarSolar.drop(columns=['ElectricityUsage', 'SystemSize', 'SystemType', 'SolarPanel',
       'Inverter', 'Battery ', 'NoOfBatteries ', 'NoOfInveters ', 'NoOfPanels'])

cleanSolar.head(3)

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

def suggest(input):
  vc = CountVectorizer()
  cleanSolar['Tags'] = cleanSolar['Tags'].fillna('')
  tags = vc.fit_transform(cleanSolar['Tags'])
  user_input = vc.transform([" ".join(input)])
  similarities = cosine_similarity(user_input, tags)
  top_three = similarities.argsort()[0][::-1][:3]
  results = cleanSolar.loc[top_three, 'SolarSystem'].values
  for i, solar in enumerate(results, start=1):
      print(f"Solar System {i}: {solar}")

suggest(["121-240 On Grid JA Solar"])

suggest(["0-120 On Grid JA Solar"])